CREATE TABLE `mall_products` (
  `productId`       VARCHAR(32)  NOT NULL,
  `keyImage`        VARCHAR(512) NOT NULL,
  `title`           VARCHAR(255) NOT NULL,
  `price`           INT UNSIGNED NOT NULL,
  `badges`          JSON         NULL,
  `sizes`           JSON         NULL,
  `disabledSizes`   JSON         NULL,
  `reviewRating`    DECIMAL(3,1) UNSIGNED NOT NULL DEFAULT 0.0,
  `reviewCount`     INT UNSIGNED NOT NULL DEFAULT 0,
  `isSoldOut`       TINYINT(1)   NOT NULL DEFAULT 0,
  `priceBefore`     INT UNSIGNED NOT NULL DEFAULT 0,
  `saleRate`        TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `isNew`           TINYINT(1)   NOT NULL DEFAULT 0,
  `isBest`          TINYINT(1)   NOT NULL DEFAULT 0,
  `category`        VARCHAR(32)  NOT NULL,
  `thumbs`          JSON         NULL,
  `titleEn`         VARCHAR(255) NULL,
  PRIMARY KEY (`productId`),
  KEY `idx_category` (`category`),
  KEY `idx_isNew` (`isNew`),
  KEY `idx_isBest` (`isBest`),
  KEY `idx_isSoldOut` (`isSoldOut`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
